#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18

// Neutralize left alt, left GUI, right GUI and left GUI+ESC
#define MODS_TO_NEUTRALIZE {MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI), MOD_BIT(KC_LEFT_GUI) | MOD_BIT(KC_ESC)}